### ISSUE TITLE
Can't start debug after opening the folder in VSCode (MacOS)

### ISSUE THREAD

**Issue by Ephasme** [microsoft/vscode-remote-try-rust#3]
Steps to reproduce:
- Clone the repository
- Open VSCode and "Open Folder in Container"
- Press F5 in order to start debugging

VSCode's CodeLLDB extension complains about handshake : "The debugger exited without completing startup handshake."

Log : 

```
Running `cargo build --bin=hello_remote_world --package=hello_remote_world --manifest-path=Cargo.toml --message-format=json`...
   Compiling hello_remote_world v0.1.0 (/workspaces/vscode-remote-try-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 1.07s
Raw artifacts:
{ fileName:
   '/workspaces/vscode-remote-try-rust/target/debug/hello_remote_world',
  name: 'hello_remote_world',
  kind: 'bin' }
Filtered artifacts: 
{ fileName:
   '/workspaces/vscode-remote-try-rust/target/debug/hello_remote_world',
  name: 'hello_remote_world',
  kind: 'bin' }
configuration: { type: 'lldb',
  request: 'launch',
  name: 'Debug executable',
  args: [],
  relativePathBase: '/workspaces/vscode-remote-try-rust',
  program:
   '/workspaces/vscode-remote-try-rust/target/debug/hello_remote_world',
  sourceLanguages: [ 'rust' ] }
/home/vscode/.vscode-server/extensions/vadimcn.vscode-lldb-1.3.0/lldb/bin/lldb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
Error: The debugger exited without completing startup handshake.
--- Checking version ---
{ [Error: spawn lldb ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb',
  path: 'lldb',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-10.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-10.0',
  path: 'lldb-10.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-9.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-9.0',
  path: 'lldb-9.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-8.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-8.0',
  path: 'lldb-8.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-7.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-7.0',
  path: 'lldb-7.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-6.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-6.0',
  path: 'lldb-6.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-5.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-5.0',
  path: 'lldb-5.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-4.0 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-4.0',
  path: 'lldb-4.0',
  spawnargs: [ '-v' ] }
{ [Error: spawn lldb-3.9 ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)]
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn lldb-3.9',
  path: 'lldb-3.9',
  spawnargs: [ '-v' ] }
--- Done ---
```

**Comment by Chuxel** [comment]
Thanks for reporting - it looks like the base image updated which caused the lldb package name to change since it updated from Debian 9 to 10.  

I just pushed an update

**Comment by Ephasme** [comment]
Thanks a lot @Chuxel for your incredible responsiveness, it works as expected now.
